"""add route environment evidence persistence

Revision ID: 4c2e8a9f1b73
Revises: e5f3ec7e1790
Create Date: 2026-10-04

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "4c2e8a9f1b73"
down_revision: Union[str, None] = "e5f3ec7e1790"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "route_environment_evidence_sets",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "workout_session_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "schema_version",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "evidence_hash",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "session_external_id",
            sa.String(length=256),
            nullable=True,
        ),
        sa.Column(
            "is_current",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "scope",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "source_summary",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "replaced_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workout_session_id"],
            ["workout_sessions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id"
        ),
        sa.UniqueConstraint(
            "workout_session_id",
            "evidence_hash",
            name="uq_route_environment_session_hash",
        ),
    )

    op.create_index(
        op.f(
            "ix_route_environment_evidence_sets_user_id"
        ),
        "route_environment_evidence_sets",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_route_environment_evidence_sets_workout_session_id"
        ),
        "route_environment_evidence_sets",
        ["workout_session_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_route_environment_evidence_sets_session_external_id"
        ),
        "route_environment_evidence_sets",
        ["session_external_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_route_environment_evidence_sets_is_current"
        ),
        "route_environment_evidence_sets",
        ["is_current"],
        unique=False,
    )

    op.create_table(
        "route_environment_routes",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "evidence_set_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "route_key",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "route_index",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "exercise_index",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "segment_record_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "quality_provenance",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "time_context",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "route_semantics",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_set_id"],
            ["route_environment_evidence_sets.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id"
        ),
        sa.UniqueConstraint(
            "evidence_set_id",
            "route_key",
            name="uq_route_environment_route_key",
        ),
    )

    op.create_index(
        op.f(
            "ix_route_environment_routes_evidence_set_id"
        ),
        "route_environment_routes",
        ["evidence_set_id"],
        unique=False,
    )

    op.create_table(
        "route_environment_weather_samples",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "evidence_set_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "source_provider",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "source_product",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "source_type",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "source_sample_id",
            sa.String(length=512),
            nullable=False,
        ),
        sa.Column(
            "sampled_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "latitude_deg",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "longitude_deg",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "elevation_m",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "air_temperature_c",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "wind_speed_mps",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "wind_direction_from_deg",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "wind_gust_mps",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "temporal_resolution_seconds",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "spatial_support",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "source_reference",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "extra_data",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_set_id"],
            ["route_environment_evidence_sets.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id"
        ),
        sa.UniqueConstraint(
            "evidence_set_id",
            "source_provider",
            "source_sample_id",
            name="uq_route_environment_weather_source",
        ),
    )

    op.create_index(
        op.f(
            "ix_route_environment_weather_samples_evidence_set_id"
        ),
        "route_environment_weather_samples",
        ["evidence_set_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_route_environment_weather_samples_sampled_at"
        ),
        "route_environment_weather_samples",
        ["sampled_at"],
        unique=False,
    )

    op.create_table(
        "route_environment_hydrology_measurements",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "evidence_set_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "source_provider",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "source_product",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "source_type",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "source_measurement_id",
            sa.String(length=512),
            nullable=False,
        ),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "metric_key",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "metric_code",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "value",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "unit",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "provider_data_type",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "data_quality_code",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "field_quality_code",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "station_registry_id",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "station_name",
            sa.String(length=200),
            nullable=True,
        ),
        sa.Column(
            "watercourse",
            sa.String(length=200),
            nullable=True,
        ),
        sa.Column(
            "municipality",
            sa.String(length=200),
            nullable=True,
        ),
        sa.Column(
            "station_latitude_deg",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "station_longitude_deg",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "river_km",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "extra_data",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_set_id"],
            ["route_environment_evidence_sets.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id"
        ),
        sa.UniqueConstraint(
            "evidence_set_id",
            "source_provider",
            "source_measurement_id",
            name="uq_route_environment_hydrology_source",
        ),
    )

    op.create_index(
        op.f(
            "ix_route_environment_hydrology_measurements_evidence_set_id"
        ),
        "route_environment_hydrology_measurements",
        ["evidence_set_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_route_environment_hydrology_measurements_observed_at"
        ),
        "route_environment_hydrology_measurements",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_route_environment_hydrology_measurements_metric_key"
        ),
        "route_environment_hydrology_measurements",
        ["metric_key"],
        unique=False,
    )

    op.create_table(
        "route_environment_segments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "evidence_set_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "route_evidence_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "record_id",
            sa.String(length=512),
            nullable=False,
        ),
        sa.Column(
            "order_index",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "view_segment_index",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "segment_index_scope",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "source_segment_index",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "source_segment_index_scope",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "source_segment_index_status",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "source_waypoint_contiguous",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "start_waypoint_index",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "end_waypoint_index",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "start_exercise_elapsed_ms",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "end_exercise_elapsed_ms",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "start_timestamp",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "midpoint_timestamp",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "end_timestamp",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "start_latitude_deg",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "start_longitude_deg",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "end_latitude_deg",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "end_longitude_deg",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "surface_distance_m",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "movement_bearing_deg",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "position_status",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "gps_ground_speed_mps",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "ground_speed_change_rate_mps2",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "cumulative_trusted_surface_distance_m",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "weather_sample_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "weather_match_status",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "weather_time_delta_seconds",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "weather_surface_distance_m",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "wind_status",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "headwind_component_mps",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "tailwind_component_mps",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "crosswind_magnitude_mps",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "relative_air_velocity_along_course_mps",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "relative_air_velocity_cross_course_mps",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "relative_air_speed_mps",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "water_level_measurement_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "water_level_status",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "water_level_time_delta_seconds",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "discharge_measurement_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "discharge_status",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "discharge_time_delta_seconds",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "water_temperature_measurement_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "water_temperature_status",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "water_temperature_time_delta_seconds",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "station_surface_distance_m",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "current_speed_estimate_mps",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "current_direction_deg",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "waterbody_identity_status",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "waterbody_id",
            sa.String(length=256),
            nullable=True,
        ),
        sa.Column(
            "river_reach_id",
            sa.String(length=256),
            nullable=True,
        ),
        sa.Column(
            "flow_relation",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "route_corridor_id",
            sa.String(length=256),
            nullable=True,
        ),
        sa.Column(
            "route_choice_status",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "route_choice_intent",
            sa.String(length=256),
            nullable=True,
        ),
        sa.Column(
            "group_tactical_context",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "preferred_flow_line",
            sa.String(length=256),
            nullable=True,
        ),
        sa.Column(
            "extra_data",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_set_id"],
            ["route_environment_evidence_sets.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["route_evidence_id"],
            ["route_environment_routes.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["weather_sample_id"],
            ["route_environment_weather_samples.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["water_level_measurement_id"],
            ["route_environment_hydrology_measurements.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["discharge_measurement_id"],
            ["route_environment_hydrology_measurements.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["water_temperature_measurement_id"],
            ["route_environment_hydrology_measurements.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "evidence_set_id",
            "record_id",
            name="uq_route_environment_segment_record",
        ),
    )

    op.create_index(
        op.f(
            "ix_route_environment_segments_evidence_set_id"
        ),
        "route_environment_segments",
        ["evidence_set_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_route_environment_segments_route_evidence_id"
        ),
        "route_environment_segments",
        ["route_evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_route_environment_segments_source_segment_index"
        ),
        "route_environment_segments",
        ["source_segment_index"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_route_environment_segments_weather_sample_id"
        ),
        "route_environment_segments",
        ["weather_sample_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_route_environment_segments_water_level_measurement_id"
        ),
        "route_environment_segments",
        ["water_level_measurement_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_route_environment_segments_discharge_measurement_id"
        ),
        "route_environment_segments",
        ["discharge_measurement_id"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_route_environment_segments_water_temperature_measurement_id"
        ),
        "route_environment_segments",
        ["water_temperature_measurement_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        op.f(
            "ix_route_environment_segments_water_temperature_measurement_id"
        ),
        table_name="route_environment_segments",
    )
    op.drop_index(
        op.f(
            "ix_route_environment_segments_discharge_measurement_id"
        ),
        table_name="route_environment_segments",
    )
    op.drop_index(
        op.f(
            "ix_route_environment_segments_water_level_measurement_id"
        ),
        table_name="route_environment_segments",
    )
    op.drop_index(
        op.f(
            "ix_route_environment_segments_weather_sample_id"
        ),
        table_name="route_environment_segments",
    )
    op.drop_index(
        op.f(
            "ix_route_environment_segments_source_segment_index"
        ),
        table_name="route_environment_segments",
    )
    op.drop_index(
        op.f(
            "ix_route_environment_segments_route_evidence_id"
        ),
        table_name="route_environment_segments",
    )
    op.drop_index(
        op.f(
            "ix_route_environment_segments_evidence_set_id"
        ),
        table_name="route_environment_segments",
    )
    op.drop_table(
        "route_environment_segments"
    )

    op.drop_index(
        op.f(
            "ix_route_environment_hydrology_measurements_metric_key"
        ),
        table_name=(
            "route_environment_hydrology_measurements"
        ),
    )
    op.drop_index(
        op.f(
            "ix_route_environment_hydrology_measurements_observed_at"
        ),
        table_name=(
            "route_environment_hydrology_measurements"
        ),
    )
    op.drop_index(
        op.f(
            "ix_route_environment_hydrology_measurements_evidence_set_id"
        ),
        table_name=(
            "route_environment_hydrology_measurements"
        ),
    )
    op.drop_table(
        "route_environment_hydrology_measurements"
    )

    op.drop_index(
        op.f(
            "ix_route_environment_weather_samples_sampled_at"
        ),
        table_name=(
            "route_environment_weather_samples"
        ),
    )
    op.drop_index(
        op.f(
            "ix_route_environment_weather_samples_evidence_set_id"
        ),
        table_name=(
            "route_environment_weather_samples"
        ),
    )
    op.drop_table(
        "route_environment_weather_samples"
    )

    op.drop_index(
        op.f(
            "ix_route_environment_routes_evidence_set_id"
        ),
        table_name="route_environment_routes",
    )
    op.drop_table(
        "route_environment_routes"
    )

    op.drop_index(
        op.f(
            "ix_route_environment_evidence_sets_is_current"
        ),
        table_name=(
            "route_environment_evidence_sets"
        ),
    )
    op.drop_index(
        op.f(
            "ix_route_environment_evidence_sets_session_external_id"
        ),
        table_name=(
            "route_environment_evidence_sets"
        ),
    )
    op.drop_index(
        op.f(
            "ix_route_environment_evidence_sets_workout_session_id"
        ),
        table_name=(
            "route_environment_evidence_sets"
        ),
    )
    op.drop_index(
        op.f(
            "ix_route_environment_evidence_sets_user_id"
        ),
        table_name=(
            "route_environment_evidence_sets"
        ),
    )
    op.drop_table(
        "route_environment_evidence_sets"
    )
