"""add physiological measurements

Revision ID: 5f4ea45abaea
Revises: 89e425c19a0e
Create Date: 2026-09-30 11:01:57.072605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4ea45abaea'
down_revision: Union[str, Sequence[str], None] = '89e425c19a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physiological_measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('value_float', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('device_model', sa.String(length=128), nullable=True),
    sa.Column('quality', sa.String(length=32), nullable=True),
    sa.Column('source_record_id', sa.String(length=256), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physiological_measurements_measured_at'), 'physiological_measurements', ['measured_at'], unique=False)
    op.create_index(op.f('ix_physiological_measurements_metric_key'), 'physiological_measurements', ['metric_key'], unique=False)
    op.create_index(op.f('ix_physiological_measurements_provider'), 'physiological_measurements', ['provider'], unique=False)
    op.create_index(op.f('ix_physiological_measurements_source_record_id'), 'physiological_measurements', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_physiological_measurements_user_id'), 'physiological_measurements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_physiological_measurements_user_id'), table_name='physiological_measurements')
    op.drop_index(op.f('ix_physiological_measurements_source_record_id'), table_name='physiological_measurements')
    op.drop_index(op.f('ix_physiological_measurements_provider'), table_name='physiological_measurements')
    op.drop_index(op.f('ix_physiological_measurements_metric_key'), table_name='physiological_measurements')
    op.drop_index(op.f('ix_physiological_measurements_measured_at'), table_name='physiological_measurements')
    op.drop_table('physiological_measurements')
    # ### end Alembic commands ###
