"""add training periods

Revision ID: 7b4747788e15
Revises: 0001
Create Date: 2026-09-29 12:15:12.840172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4747788e15'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('period_type', sa.Enum('OLYMPIC_CYCLE', 'SEASON', 'MACROCYCLE', 'MESOCYCLE', name='period_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_load', sa.Float(), nullable=True),
    sa.Column('load_method', sa.String(length=32), nullable=True),
    sa.Column('target_duration_sec', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['training_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_periods_end_date'), 'training_periods', ['end_date'], unique=False)
    op.create_index(op.f('ix_training_periods_parent_id'), 'training_periods', ['parent_id'], unique=False)
    op.create_index(op.f('ix_training_periods_period_type'), 'training_periods', ['period_type'], unique=False)
    op.create_index(op.f('ix_training_periods_start_date'), 'training_periods', ['start_date'], unique=False)
    op.create_index(op.f('ix_training_periods_user_id'), 'training_periods', ['user_id'], unique=False)
    op.create_table('training_period_objectives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('objective_type', sa.Enum('ENDURANCE', 'SPEED', 'STRENGTH', 'TECHNIQUE', 'RECOVERY', 'MOBILITY', 'RACE_SPECIFIC', name='objective_type_enum'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['training_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'objective_type', name='uq_period_objective_type')
    )
    op.create_index(op.f('ix_training_period_objectives_period_id'), 'training_period_objectives', ['period_id'], unique=False)
    op.add_column('planned_workouts', sa.Column('training_period_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_planned_workouts_training_period_id'), 'planned_workouts', ['training_period_id'], unique=False)
    op.create_foreign_key(
        'fk_planned_workouts_training_period_id_training_periods',
        'planned_workouts',
        'training_periods',
        ['training_period_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        'fk_planned_workouts_training_period_id_training_periods',
        'planned_workouts',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_planned_workouts_training_period_id'), table_name='planned_workouts')
    op.drop_column('planned_workouts', 'training_period_id')
    op.drop_index(op.f('ix_training_period_objectives_period_id'), table_name='training_period_objectives')
    op.drop_table('training_period_objectives')
    op.drop_index(op.f('ix_training_periods_user_id'), table_name='training_periods')
    op.drop_index(op.f('ix_training_periods_start_date'), table_name='training_periods')
    op.drop_index(op.f('ix_training_periods_period_type'), table_name='training_periods')
    op.drop_index(op.f('ix_training_periods_parent_id'), table_name='training_periods')
    op.drop_index(op.f('ix_training_periods_end_date'), table_name='training_periods')
    op.drop_table('training_periods')
    # ### end Alembic commands ###
