"""link capacity to measurement

Revision ID: 89e425c19a0e
Revises: cbb9201dcd75
Create Date: 2026-09-30 09:14:44.119552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e425c19a0e'
down_revision: Union[str, Sequence[str], None] = 'cbb9201dcd75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete_capacities', sa.Column('measurement_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_athlete_capacities_measurement_id'), 'athlete_capacities', ['measurement_id'], unique=False)
    op.create_foreign_key(
        "athlete_capacities_measurement_id_fkey",
        "athlete_capacities",
        "measurements",
        ["measurement_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        "athlete_capacities_measurement_id_fkey",
        "athlete_capacities",
        type_="foreignkey",
    )
    op.drop_index(op.f('ix_athlete_capacities_measurement_id'), table_name='athlete_capacities')
    op.drop_column('athlete_capacities', 'measurement_id')
    # ### end Alembic commands ###
