"""add athlete state models

Revision ID: cbb9201dcd75
Revises: 9c0fd62617ab
Create Date: 2026-09-30 08:24:36.455231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb9201dcd75'
down_revision: Union[str, Sequence[str], None] = '9c0fd62617ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_type', sa.Enum('TRAINING_HISTORY', 'VO2MAX_TEST', 'LACTATE_TEST', 'PERFORMANCE_TEST', 'STRENGTH_TEST', 'BODY_COMPOSITION', 'OTHER', name='assessment_type_enum'), nullable=False),
    sa.Column('sport', sa.Enum('KAYAK', 'RUNNING', 'SWIMMING', 'STRENGTH', 'CYCLING', 'OTHER', name='assessment_sport_enum'), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_assessment_type'), 'assessments', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_assessments_performed_at'), 'assessments', ['performed_at'], unique=False)
    op.create_index(op.f('ix_assessments_user_id'), 'assessments', ['user_id'], unique=False)
    op.create_table('athlete_readiness',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('hrv_rmssd_ms', sa.Float(), nullable=True),
    sa.Column('resting_hr_bpm', sa.Float(), nullable=True),
    sa.Column('sleep_duration_sec', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('energy_score', sa.Float(), nullable=True),
    sa.Column('fatigue_score', sa.Float(), nullable=True),
    sa.Column('stress_score', sa.Float(), nullable=True),
    sa.Column('soreness_score', sa.Float(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('illness', sa.Boolean(), nullable=False),
    sa.Column('travel', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recorded_date', name='uq_readiness_user_date')
    )
    op.create_index(op.f('ix_athlete_readiness_recorded_date'), 'athlete_readiness', ['recorded_date'], unique=False)
    op.create_index(op.f('ix_athlete_readiness_user_id'), 'athlete_readiness', ['user_id'], unique=False)
    op.create_table('athlete_capacities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('capacity_type', sa.Enum('GENERAL_AEROBIC', 'SPORT_SPECIFIC_AEROBIC', 'STRENGTH', 'MUSCULAR_ENDURANCE', 'NEUROMUSCULAR', 'TECHNIQUE', name='capacity_type_enum'), nullable=False),
    sa.Column('sport', sa.Enum('KAYAK', 'RUNNING', 'SWIMMING', 'STRENGTH', 'CYCLING', 'OTHER', name='capacity_sport_enum'), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('source', sa.Enum('ASSESSMENT', 'TRAINING_INFERENCE', 'SELF_REPORTED', 'MANUAL', name='capacity_source_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('estimated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_capacities_assessment_id'), 'athlete_capacities', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_athlete_capacities_capacity_type'), 'athlete_capacities', ['capacity_type'], unique=False)
    op.create_index(op.f('ix_athlete_capacities_estimated_at'), 'athlete_capacities', ['estimated_at'], unique=False)
    op.create_index(op.f('ix_athlete_capacities_source'), 'athlete_capacities', ['source'], unique=False)
    op.create_index(op.f('ix_athlete_capacities_sport'), 'athlete_capacities', ['sport'], unique=False)
    op.create_index(op.f('ix_athlete_capacities_user_id'), 'athlete_capacities', ['user_id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('value_float', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('sport', sa.Enum('KAYAK', 'RUNNING', 'SWIMMING', 'STRENGTH', 'CYCLING', 'OTHER', name='measurement_sport_enum'), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_assessment_id'), 'measurements', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_measurements_metric_key'), 'measurements', ['metric_key'], unique=False)
    op.create_table('athlete_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workout_session_id', sa.Uuid(), nullable=True),
    sa.Column('response_timing', sa.Enum('IMMEDIATE', 'SAME_DAY', 'NEXT_MORNING', 'FOLLOW_UP', name='response_timing_enum'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fatigue_score', sa.Float(), nullable=True),
    sa.Column('soreness_score', sa.Float(), nullable=True),
    sa.Column('recovery_score', sa.Float(), nullable=True),
    sa.Column('energy_score', sa.Float(), nullable=True),
    sa.Column('performance_metric', sa.String(length=64), nullable=True),
    sa.Column('performance_delta_percent', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_responses_recorded_at'), 'athlete_responses', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_athlete_responses_response_timing'), 'athlete_responses', ['response_timing'], unique=False)
    op.create_index(op.f('ix_athlete_responses_user_id'), 'athlete_responses', ['user_id'], unique=False)
    op.create_index(op.f('ix_athlete_responses_workout_session_id'), 'athlete_responses', ['workout_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_athlete_responses_workout_session_id'), table_name='athlete_responses')
    op.drop_index(op.f('ix_athlete_responses_user_id'), table_name='athlete_responses')
    op.drop_index(op.f('ix_athlete_responses_response_timing'), table_name='athlete_responses')
    op.drop_index(op.f('ix_athlete_responses_recorded_at'), table_name='athlete_responses')
    op.drop_table('athlete_responses')
    op.drop_index(op.f('ix_measurements_metric_key'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_assessment_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_athlete_capacities_user_id'), table_name='athlete_capacities')
    op.drop_index(op.f('ix_athlete_capacities_sport'), table_name='athlete_capacities')
    op.drop_index(op.f('ix_athlete_capacities_source'), table_name='athlete_capacities')
    op.drop_index(op.f('ix_athlete_capacities_estimated_at'), table_name='athlete_capacities')
    op.drop_index(op.f('ix_athlete_capacities_capacity_type'), table_name='athlete_capacities')
    op.drop_index(op.f('ix_athlete_capacities_assessment_id'), table_name='athlete_capacities')
    op.drop_table('athlete_capacities')
    op.drop_index(op.f('ix_athlete_readiness_user_id'), table_name='athlete_readiness')
    op.drop_index(op.f('ix_athlete_readiness_recorded_date'), table_name='athlete_readiness')
    op.drop_table('athlete_readiness')
    op.drop_index(op.f('ix_assessments_user_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_performed_at'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessment_type'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
