"""add provider data records

Revision ID: e5f3ec7e1790
Revises: 5f4ea45abaea
Create Date: 2026-09-30 11:15:34.537188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f3ec7e1790'
down_revision: Union[str, Sequence[str], None] = '5f4ea45abaea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_data_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('data_type', sa.String(length=64), nullable=False),
    sa.Column('provider_record_id', sa.String(length=256), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_data_records_data_type'), 'provider_data_records', ['data_type'], unique=False)
    op.create_index(op.f('ix_provider_data_records_occurred_at'), 'provider_data_records', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_provider_data_records_provider'), 'provider_data_records', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_data_records_provider_record_id'), 'provider_data_records', ['provider_record_id'], unique=False)
    op.create_index(op.f('ix_provider_data_records_user_id'), 'provider_data_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_data_records_user_id'), table_name='provider_data_records')
    op.drop_index(op.f('ix_provider_data_records_provider_record_id'), table_name='provider_data_records')
    op.drop_index(op.f('ix_provider_data_records_provider'), table_name='provider_data_records')
    op.drop_index(op.f('ix_provider_data_records_occurred_at'), table_name='provider_data_records')
    op.drop_index(op.f('ix_provider_data_records_data_type'), table_name='provider_data_records')
    op.drop_table('provider_data_records')
    # ### end Alembic commands ###
